stages:
  - test

test-ruby31:
  stage: test
  image: ruby:3.1.2
  script:
    - bundle install
    - sh bin/run-tests.sh

test-ruby32:
  stage: test
  image: ruby:3.2.0
  script:
    - bundle install
    - sh bin/run-tests.sh
