##
# Plugins
require:
  - standard

##
# Defaults: standard-rb
inherit_gem:
  standard: config/base.yml

##
# Rubocop scope
AllCops:
  Include:
    - "lib/**/*.rb"
    - "test/**/*.rb"
  TargetRubyVersion: 3.1

##
# Disabled cops
Layout/MultilineMethodCallIndentation:
  Enabled: false
Layout/MultilineOperationIndentation:
  Enabled: false
Layout/ArgumentAlignment:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/Not:
  Enabled: false
