##
# Plugins
require:
  - standard

##
# Defaults (standardrb)
inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  Include:
    - "lib/**/*.rb"
    - "test/**/*.rb"

Layout/MultilineOperationIndentation:
  Exclude:
    - "lib/trip/fiber.rb"

Layout/ArgumentAlignment:
  Exclude:
    - "test/readme_examples_test.rb"
